// ============================================================
// Supabase Database Types
//
// This file should be auto-generated by the Supabase CLI:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
//
// For now, this is a minimal placeholder. Replace it after running the schema.
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          emoji: string;
          onboarded: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string;
          emoji?: string;
          onboarded?: boolean;
        };
        Update: {
          name?: string;
          emoji?: string;
          onboarded?: boolean;
        };
      };
      parties: {
        Row: {
          id: string;
          name: string;
          invite_code: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          name?: string;
          created_by?: string | null;
        };
        Update: {
          name?: string;
        };
      };
      party_members: {
        Row: {
          party_id: string;
          user_id: string;
          role: 'owner' | 'member';
          joined_at: string;
        };
        Insert: {
          party_id: string;
          user_id: string;
          role?: 'owner' | 'member';
        };
        Update: { role?: 'owner' | 'member' };
      };
      tasks: {
        Row: {
          id: string;
          party_id: string;
          name: string;
          emoji: string;
          cycle: number;
          weight: number;
          assigned_to: string | null;
          last_done_at: string | null;
          last_done_by: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          party_id: string;
          name: string;
          emoji?: string;
          cycle?: number;
          weight?: number;
          assigned_to?: string | null;
          created_by?: string | null;
        };
        Update: {
          name?: string;
          emoji?: string;
          cycle?: number;
          weight?: number;
          assigned_to?: string | null;
          last_done_at?: string | null;
          last_done_by?: string | null;
        };
      };
      verifications: {
        Row: {
          id: string;
          task_id: string;
          party_id: string;
          requested_by: string;
          photo_url: string | null;
          photo_placeholder: string | null;
          status: 'pending' | 'approved' | 'rejected';
          resolved_by: string | null;
          resolved_at: string | null;
          reject_reason: string | null;
          requested_at: string;
        };
        Insert: {
          task_id: string;
          party_id: string;
          requested_by: string;
          photo_url?: string | null;
          photo_placeholder?: string | null;
        };
        Update: {
          status?: 'pending' | 'approved' | 'rejected';
          resolved_by?: string | null;
          resolved_at?: string | null;
          reject_reason?: string | null;
        };
      };
      scores: {
        Row: { party_id: string; user_id: string; score: number; updated_at: string };
        Insert: { party_id: string; user_id: string; score?: number };
        Update: { score?: number };
      };
      streaks: {
        Row: {
          party_id: string;
          current: number;
          longest: number;
          last_active_date: string | null;
          freezes: number;
          updated_at: string;
        };
        Insert: { party_id: string };
        Update: {
          current?: number;
          longest?: number;
          last_active_date?: string | null;
          freezes?: number;
        };
      };
      activity: {
        Row: {
          id: string;
          party_id: string;
          type: string;
          actor_id: string | null;
          target_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          party_id: string;
          type: string;
          actor_id?: string | null;
          target_id?: string | null;
          metadata?: Json;
        };
        Update: never;
      };
      user_badges: {
        Row: {
          user_id: string;
          badge_id: string;
          party_id: string | null;
          earned_at: string;
        };
        Insert: { user_id: string; badge_id: string; party_id?: string | null };
        Update: never;
      };
      notification_settings: {
        Row: {
          user_id: string;
          enabled: boolean;
          verification_requests: boolean;
          task_reminders: boolean;
          streak_reminders: boolean;
          party_updates: boolean;
          quiet_hours_enabled: boolean;
          quiet_hours_start: string;
          quiet_hours_end: string;
          updated_at: string;
        };
        Insert: { user_id: string };
        Update: Partial<{
          enabled: boolean;
          verification_requests: boolean;
          task_reminders: boolean;
          streak_reminders: boolean;
          party_updates: boolean;
          quiet_hours_enabled: boolean;
          quiet_hours_start: string;
          quiet_hours_end: string;
        }>;
      };
      user_totals: {
        Row: {
          user_id: string;
          requested_count: number;
          approved_count: number;
          rejected_count: number;
          updated_at: string;
        };
        Insert: { user_id: string };
        Update: Partial<{
          requested_count: number;
          approved_count: number;
          rejected_count: number;
        }>;
      };
    };
    Functions: {
      approve_verification: {
        Args: { p_verification_id: string };
        Returns: Json;
      };
      reject_verification: {
        Args: { p_verification_id: string; p_reason: string };
        Returns: Json;
      };
      create_verification: {
        Args: { p_task_id: string; p_photo_placeholder?: string; p_photo_url?: string };
        Returns: string;
      };
      join_party: {
        Args: { p_invite_code: string };
        Returns: string;
      };
      get_party_by_invite_code: {
        Args: { p_code: string };
        Returns: { id: string; name: string }[];
      };
      calculate_room_score: {
        Args: { p_party_id: string };
        Returns: number;
      };
    };
  };
}
